apiVersion: v1
kind: ReplicationController
metadata:
  name: demo51
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo51
  template:
    metadata:
      labels:
        app: demo51
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo51
        image: ${docker-registry}/${docker-namespace}/demo51:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080